spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:produtos
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2ialect
  h2:
    console:
      enabled: true
      path: /h2-console
